In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

Logistic Regression

In [7]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


0.9462962962962963

SVM

In [8]:
svm=SVC(gamma='auto')
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.3296296296296296

Random Forest Classofier

In [9]:
rfc=RandomForestClassifier(n_estimators=40)
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.9666666666666667

K-Fold Validation

In [10]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


Use KFold for our digits example

In [12]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [14]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

score_lr=[]
score_svm=[]
score_rfc=[]

for train_index,test_index in kf.split(digits.data):
    X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
        digits.target[train_index],digits.target[test_index]
    score_lr.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(gamma='auto'),X_train,X_test,y_train,y_test))
    score_rfc.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [15]:
score_lr

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [16]:
score_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [17]:
score_rfc

[0.9382303839732888, 0.9449081803005008, 0.9131886477462438]

cross_val_score function

In [18]:
from sklearn.model_selection import cross_val_score

In [19]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),digits.data,digits.target,cv=3)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


array([0.89482471, 0.95325543, 0.90984975])

In [20]:
cross_val_score(SVC(gamma='auto'),digits.data,digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [21]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target,cv=3)
#

array([0.92320534, 0.94490818, 0.92821369])

Parameter tunning using k fold cross validation

In [29]:
score1=cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target,cv=3)
np.average(score1)

0.8530884808013356

In [28]:
score2=cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target,cv=3)
np.average(score2)

0.9198664440734557

In [30]:
score3=cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target,cv=3)
np.average(score3)

0.9348914858096827